################## 系统配置 ##################

search:
  includes:
    - post
    - page

vendors:
  npm_cdn: https://unpkg.com/
  packages:
    hexo-theme-kratos-rebirth:
      cdn_url: null

################## 样式配置 ##################

# 图片配置
image:
  favicon: "/favicon.ico"
  avatar: "/images/avatar.jpg"
  banner:
    light: "/images/banner.webp"
    dark: "/images/banner_dark.webp"
  background:
    light: "/images/bg.webp"
    dark: "/images/bg_dark.webp"
  about:
    light: "/images/about.webp"
    dark: ""

posts:
  # default_cover: "/images/default.webp"
  default_cover: null
  donate: true

pages:
  donate: true

# 顶部导航栏配置
nav:
  items:
    - label: 首页
      icon: home
      url: /
    - label: 档案馆
      icon: file
      url: /archives/
    - label: 友人帐
      icon: paw
      url: /friends/
    - label: 溯源
      icon: paper-plane
      url: /about/
    - label: 开往
      icon: subway
      url: https://www.travellings.cn/go.html

# Footer 页脚配置
footer:
  links:
    - icon: telegram
      link: https://t.me/alampy
    - icon: github
      link: https://github.com/ArcticLampyrid
    - icon: rss
      link: /atom.xml
  components:
    uptime:
      since: "2016/04/28 17:03:12"
      text: "本站已运行"
    author:
      homepage: ""
    additional: # 托管信息等
      - - 由 <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a> 强力驱动
        - 在 <a href="https://aws.amazon.com/amplify/" target="_blank">Amplify</a> 暖心托管
        - <a href="https://icp.gov.moe/?keyword=20240550" target="_blank">萌ICP备20240550号</a>

inactive_notice:
  enable: false

syntax_highlighter:
  theme: null

sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "QQ"
      icon: "qq"
      color: "#00bfff"
      link: "https://connect.qq.com/widget/shareqq/index.html?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "QQ空间"
      icon: "star"
      color: "#fece00"
      link: "https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "微博"
      icon: "weibo"
      color: "#e6162d"
      link: "https://service.weibo.com/share/share.php?url=$URL&title=$TITLE"
    - name: "X"
      icon: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-x">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
          <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
        </svg>
      color: "#000"
      link: "https://x.com/intent/tweet?text=$TITLE&url=$URL"
    - name: "Facebook"
      icon: "facebook"
      color: "#3e569b"
      link: "https://www.facebook.com/sharer/sharer.php?u=$URL"

# 打赏组件设置
donate:
  enable: true
  title: "赞助喵"
  message: 非常感谢您的喜欢！<i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "/images/sponsor/afadian.webp"
  platforms:
    - name: "爱发电"
      icon: |
        <svg viewBox="0 0 160 160" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M134.614 98.3714C133.294 97.5334 131.909 97.1697 130.563 97.02C133.724 89.3002 135.736 79.1949 128.887 69.1574C118.406 53.7998 103.38 45.8198 84.2346 45.4382C78.7809 45.3312 72.3517 45.5844 65.5487 45.8554C57.6493 46.1692 47.1369 46.5793 39.9921 45.9873C41.4161 45.2136 42.9326 44.4719 44.2462 43.8336C49.2728 41.384 53.2314 39.4763 51.9214 36.0925C51.2343 34.117 49.1874 33.0794 45.8233 33.0045C38.7426 32.8441 23.4421 36.9447 20.6903 43.8586C19.1418 47.7524 18.8854 55.2689 34.5668 61.9119C41.0174 64.6503 59.237 67.9879 66.2678 68.6867C68.2542 68.8793 69.7743 69.2822 70.9277 69.7101C69.3151 70.7727 67.6597 71.8888 65.9972 73.0298C63.1102 71.3824 58.3897 69.4391 54.8654 71.846C53.502 72.7695 52.7259 74.1316 52.6903 75.6827C52.6405 77.6117 53.8081 79.498 55.1217 81.017C49.9314 85.1639 45.7343 89.1825 44.2462 92.2811C42.5873 96.0893 41.9109 102.322 45.008 108.402C48.9382 116.118 57.6279 121.499 70.8423 124.394C88.1114 128.17 103.027 124.768 112.895 119.566C118.388 116.671 122.286 113.215 124.18 110.131C124.768 110.317 125.355 110.506 125.96 110.695C126.804 110.951 127.648 111.208 128.438 111.49C131.051 112.395 133.942 112.274 136.167 111.151C136.206 111.133 136.248 111.108 136.291 111.087C137.968 110.202 139.175 108.783 139.705 107.072C141.129 102.458 137.064 99.9082 134.614 98.3714ZM64.9999 90.6681C63.4307 90.6681 62.1621 91.9382 62.1621 93.5091C62.1621 95.0836 63.4307 96.3537 64.9999 96.3537C66.5691 96.3537 67.8378 95.0836 67.8378 93.5091C67.8378 91.9382 66.5691 90.6681 64.9999 90.6681ZM91.7568 99.1965C90.1876 99.1965 88.9189 100.467 88.9189 102.038C88.9189 103.612 90.1876 104.882 91.7568 104.882C93.326 104.882 94.5946 103.612 94.5946 102.038C94.5946 100.467 93.326 99.1965 91.7568 99.1965Z"
            stroke="currentColor" fill="none" stroke-width="8px" />
        </svg>
      color: "#946ce6"
      link: "https://afdian.com/a/alampy"

# 版权说明
copyright_notice:
  in_page:
    enable_at:
      - post
      - page

# 评论系统
comments:
  core:
    enable_at: 
      - index
      - post
      - page
    template:
      _shared: |
        <script>
          window.loadComments = async () => {
            if (typeof Artalk === "undefined") {
              setTimeout(loadComments, 100);
            } else {
              const container = document.getElementById('artalk-container');
              if (!container) {
                return;
              }
              const isDark = () => {
                switch(localStorage.getItem('user-color-scheme')) {
                  case 'dark':
                    return true;
                  case 'light':
                    return false;
                  default:
                    return window.matchMedia('(prefers-color-scheme: dark)').matches;
                }
              };
              const path = container.getAttribute("data-path");
              const artalk = Artalk.init({
                el: '#artalk-container',
                pageKey: path,
                server: 'https://comments.alampy.com',
                site: '萤火之光',
                darkMode: isDark(),
              });
              updateTheme();
              window.addEventListener('pjax:success', () => {
                artalk.destroy();
              }, { once: true });
            }
          };
        </script>
      index: ""
      post: <div id="artalk-container" class="kr-comments lazy-load" data-path="$PATH"></div>
      page: <div id="artalk-container" class="kr-comments lazy-load" data-path="$PATH"></div>
  count:
    enable_at:
      []
      # - index
      # - post
    template:
      _shared: ""
      index: ""
      post: ""

# 访问数量统计
visit_count:
  enable_at:
    []
    # - index
    # - post
  template:
    _shared: ""
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: |
    <link rel="stylesheet" id="kratos-css" href="/css/shiki.css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/artalk/2.9.1/Artalk.css" integrity="sha512-lzv5ZeeK/LLJAk/8rgV7Xn/iEOMpsrlRJp1N649V5kt5psU1glxlqKzqAms684uW/m6IePP25R6AuewvOuUvQQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/artalk/2.9.1/Artalk.js" integrity="sha512-O0qr7QLHz7WKZDQ+ifyT6hsjPP3A8aJaPkrWRaOF80C4M7bM1xirQZmM82bQgcLWlidb1/PeD65PKYAtIM3eMw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "999960a09fd44d63bc39abfe9a0e55a5"}'></script>
  footer: ""
  after_footer: ""
