# Global 全局配置
site_analytics: 
hoster: <a href="https://fleek.co/" target="_blank">Fleek</a>
site_logo:
snow: false
click_animate_js: 'candy'
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
cdn: false # 请注意这里是静态资源的 CDN 来源，图片的 CDN 在下方 jsconfig.main.pic.CDN 段配置
check_update: true

vendors:
  npm_cdn: https://npm.sourcegcdn.com/
  packages:
    hexo-theme-kratos-rebirth: 
      cdn_url: null
      files:
        "source/images/thumb/":
          relocate: "https://npm.sourcegcdn.com/hexo-theme-kratos-rebirth@2.0.2/source/images/thumb/"

# 自定义样式
customStyles:
  images: {} # 图片相关设置

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  archives: /archives/
  friends: /friends/
  about: /about/

label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-file"></i>档案馆
  friends: <i class="fa fa-paw"></i>友人帐
  about: <i class="fa fa-paper-plane"></i>溯源

# Footer 页脚配置
group_link: 
contact:
  weibo: 
  mail: 
  telegram: ArcticLampyrid
  twitter: 
  facebook: 
  linkedin: 
  fediverse:
    instance: 
    username: 
  github: ArcticLampyrid
  rss: atom.xml
timenotice: 本站已运行
icp: 
psr:
  
# Post Page 文章页配置
posts:
  show_cc: true
  donate: false
  share: true
  comments: 
    provider: livere
    enableBGImage: false

livere:
  id: city
  uid: MTAyMC81NTk3MC8zMjQzMw==

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: alampy
  sitename: ArcticLampyrid
  api: https://disqusapi.alampy.workers.dev/
  apikey: Qzq8gvf6VGEIzQHYRZjmVi8caW7kIVu4gHq7jLCk8cJ6jZaU08Mj5WNDhLgUrP9X
  admin: arcticlampyrid
  adminlabel: 博主

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/client/basic.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: #后端服务器地址，必填
  visitor: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitalk 文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitalk:
  clientID: 'GitHub Application Client ID'
  clientSecret: 'GitHub Application Client Secret'
  repo: 'Kratos-Rebirth-Demo'
  owner: 'Candinya'
  admin: 
    - 'Candinya'
  distractionFreeMode: false

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitment 文档](https://github.com/imsun/gitment#methods) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitment:
  owner: 'Candinya'
  repo: 'Kratos-Rebirth-Demo'
  oauth:
    client_id: 'Your client ID'
    client_secret: 'Your client secret'

# APlayer 左下角音乐播放器
aplayer:
  enabled: true
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 7351874049
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: /images/avatar.jpg
mobile_toc: 
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    cover:
      randomAmount: 20 # 表示从1~20
      baseUrl: null
      filenameTemplate: "thumb_{no}.webp" 
    createTime: "2019/07/19 17:03:12"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: 
  baidu: 
  bing: 

# Friends 友链相关内容
friends:
  list: []
  # - name: "猫猫①号"
  #   bio: "喵~"
  #   avatar: "../images/avatar.webp"
  #   link: "#"
  verify: true # 验证每个友链的可访问性，炸了会有提示
