################## 系统配置 ##################

search:
  includes:
    - post
    - page

vendors:
  npm_cdn: https://unpkg.com/
  packages:
    hexo-theme-kratos-rebirth:
      cdn_url: null

################## 样式配置 ##################

# 图片配置
image:
  favicon: "/favicon.ico"
  avatar: "/images/avatar.jpg"
  banner:
    light: "/images/banner.webp"
    dark: "/images/banner_dark.webp"
  background:
    light: "/images/bg.webp"
    dark: "/images/bg_dark.webp"
  about:
    light: "/images/about.webp"
    dark: ""

posts:
  # default_cover: "/images/default.webp"
  default_cover: null
  donate: false

pages:
  donate: false

# 顶部导航栏配置
nav:
  items:
    - label: 首页
      icon: home
      url: /
    - label: 档案馆
      icon: file
      url: /archives/
    - label: 友人帐
      icon: paw
      url: /friends/
    - label: 溯源
      icon: paper-plane
      url: /about/
    - label: 开往
      icon: subway
      url: https://www.travellings.cn/go.html

# Footer 页脚配置
footer:
  links:
    - icon: telegram
      link: https://t.me/alampy
    - icon: github
      link: https://github.com/ArcticLampyrid
    - icon: rss
      link: /atom.xml
  components:
    uptime:
      since: "2016/04/28 17:03:12"
      text: "本站已运行"
    author:
      homepage: ""
    additional: # 托管信息等
      - - 由 <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a> 强力驱动
        - 在 <a href="https://fleek.co/" target="_blank">Fleek</a> 暖心托管
        - <a href="https://icp.gov.moe/?keyword=20240550" target="_blank">萌ICP备20240550号</a>

inactive_notice:
  enable: false

syntax_highlighter:
  theme: null

sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "QQ"
      icon: "qq"
      color: "#00bfff"
      link: "https://connect.qq.com/widget/shareqq/index.html?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "QQ空间"
      icon: "star"
      color: "#fece00"
      link: "https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "微博"
      icon: "weibo"
      color: "#e6162d"
      link: "https://service.weibo.com/share/share.php?url=$URL&title=$TITLE"
    - name: "X"
      icon: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-x">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
          <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
        </svg>
      color: "#000"
      link: "https://x.com/intent/tweet?text=$TITLE&url=$URL"
    - name: "Facebook"
      icon: "facebook"
      color: "#3e569b"
      link: "https://www.facebook.com/sharer/sharer.php?u=$URL"

# 打赏组件设置
donate:
  enable: false
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "/demo-assets/donate.webp"
  platforms:
    - name: "Ethereum"
      html: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-currency-ethereum">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M6 12l6 -9l6 9l-6 9z" />
          <path d="M6 12l6 -3l6 3l-6 2z" />
        </svg>
      color: "#8a92b2"
      qrcode: "0xexample_address"
    - name: "BitCoin"
      icon: "bitcoin"
      color: "#ee7c2f"
      qrcode: "example_address"
    - name: "支付宝"
      html: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-alipay">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M19 3h-14a2 2 0 0 0 -2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2v-14a2 2 0 0 0 -2 -2z" />
          <path d="M7 7h10" />
          <path d="M12 3v7" />
          <path d="M21 17.314c-2.971 -1.923 -15 -8.779 -15 -1.864c0 1.716 1.52 2.55 2.985 2.55c3.512 0 6.814 -5.425 6.814 -8h-6.604" />
        </svg>
      color: "#1677ff"
      qrcode: "example_alipay"
    - name: "微信支付"
      icon: "wechat"
      color: "#38ad5a"
      qrcode: "example_wechatpay"
    - name: "Credit Card"
      icon: "credit-card"
      color: "green"
      link: "https://candinya.com"

# 版权说明
copyright_notice:
  in_page:
    enable_at:
      - post
      - page

# 评论系统
comments:
  core:
    enable_at: 
      - index
      - post
      - page
    template:
      _shared: |
        <script>
          window.loadComments = async () => {
            if (typeof Artalk === "undefined") {
              setTimeout(loadComments, 100);
            } else {
              const container = document.getElementById('artalk-container');
              if (!container) {
                return;
              }
              const isDark = () => {
                switch(localStorage.getItem('user-color-scheme')) {
                  case 'dark':
                    return true;
                  case 'light':
                    return false;
                  default:
                    return window.matchMedia('(prefers-color-scheme: dark)').matches;
                }
              };
              const path = container.getAttribute("data-path");
              const artalk = Artalk.init({
                el: '#artalk-container',
                pageKey: path,
                server: 'https://comments.alampy.com',
                site: '萤火之光',
                darkMode: isDark(),
              });
              updateTheme();
              window.addEventListener('pjax:success', () => {
                artalk.destroy();
              }, { once: true });
            }
          };
        </script>
      index: ""
      post: <div id="artalk-container" class="kr-comments lazy-load" data-path="$PATH"></div>
      page: <div id="artalk-container" class="kr-comments lazy-load" data-path="$PATH"></div>
  count:
    enable_at:
      []
      # - index
      # - post
    template:
      _shared: ""
      index: ""
      post: ""

# 访问数量统计
visit_count:
  enable_at:
    []
    # - index
    # - post
  template:
    _shared: ""
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: |
    <link rel="stylesheet" id="kratos-css" href="/css/shiki.css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/artalk/2.9.1/Artalk.css" integrity="sha512-lzv5ZeeK/LLJAk/8rgV7Xn/iEOMpsrlRJp1N649V5kt5psU1glxlqKzqAms684uW/m6IePP25R6AuewvOuUvQQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/artalk/2.9.1/Artalk.js" integrity="sha512-O0qr7QLHz7WKZDQ+ifyT6hsjPP3A8aJaPkrWRaOF80C4M7bM1xirQZmM82bQgcLWlidb1/PeD65PKYAtIM3eMw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "999960a09fd44d63bc39abfe9a0e55a5"}'></script>
  footer: ""
  after_footer: ""
