################## 系统配置 ##################

search:
  includes:
    - post
    - page

vendors:
  npm_cdn: https://unpkg.com/
  packages:
    hexo-theme-kratos-rebirth:
      cdn_url: null

################## 样式配置 ##################

# 图片配置
image:
  favicon: "/favicon.ico"
  avatar: "/images/avatar.jpg"
  banner:
    light: "/images/banner.webp"
    dark: "/images/banner_dark.webp"
  background:
    light: "/images/bg.webp"
    dark: "/images/bg_dark.webp"
  about:
    light: "/images/about.webp"
    dark: ""

posts:
  # default_cover: "/images/default.webp"
  default_cover: null
  donate: false

pages:
  donate: false

# 顶部导航栏配置
nav:
  items:
    - label: 首页
      icon: home
      url: /
    - label: 档案馆
      icon: file
      url: /archives/
    - label: 友人帐
      icon: paw
      url: /friends/
    - label: 溯源
      icon: paper-plane
      url: /about/
    - label: 开往
      icon: subway
      url: https://www.travellings.cn/go.html

# Footer 页脚配置
footer:
  links:
    - icon: telegram
      link: https://t.me/alampy
    - icon: github
      link: https://github.com/ArcticLampyrid
    - icon: rss
      link: /atom.xml
  components:
    uptime:
      since: "2016/04/28 17:03:12"
      text: "本站已运行"
    author:
      homepage: ""
    additional: # 托管信息等
      - - 由 <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a> 强力驱动
        - 在 <a href="https://fleek.co/" target="_blank">Fleek</a> 暖心托管
        - <a href="https://icp.gov.moe/?keyword=20240550" target="_blank">萌ICP备20240550号</a>

inactive_notice:
  enable: false

syntax_highlighter:
   theme: night-eighties

sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "QQ"
      icon: "qq"
      color: "#00bfff"
      link: "https://connect.qq.com/widget/shareqq/index.html?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "QQ空间"
      icon: "star"
      color: "#fece00"
      link: "https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "微博"
      icon: "weibo"
      color: "#e6162d"
      link: "https://service.weibo.com/share/share.php?url=$URL&title=$TITLE"
    - name: "X"
      html: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-x">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
          <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
        </svg>
      color: "#000"
      link: "https://x.com/intent/tweet?text=$TITLE&url=$URL"
    - name: "Facebook"
      icon: "facebook"
      color: "#3e569b"
      link: "https://www.facebook.com/sharer/sharer.php?u=$URL"
    - name: "喵窝"
      html: <svg fill="currentColor" width="18" height="18" viewBox="0 0 329 388"><path d="M0,36.226c0,-19.993 16.233,-36.226 36.226,-36.226c13.788,0 25.787,7.719 31.908,19.068l188.366,229.845l0,-111.259c-6.356,5.508 -14.645,8.843 -23.707,8.843c-19.994,0 -36.226,-16.232 -36.226,-36.226c-0,-8.551 2.968,-16.413 7.93,-22.613l-0.015,-0.013l56.614,-69.08c6.2,-11.073 18.047,-18.565 31.63,-18.565c19.994,0 36.227,16.233 36.227,36.226l-0,314.644c-0,19.994 -16.233,36.226 -36.227,36.226c-13.166,0 -24.701,-7.039 -31.044,-17.555l-189.229,-230.899l-0,212.228c-0,19.994 -16.233,36.226 -36.227,36.226c-19.993,0 -36.226,-16.232 -36.226,-36.226l0,-314.644Z" /></svg>
      color: "#62b6e7"
      link: "https://nya.one/share?text=%3E%20$TITLE%0A%3E%0A%3E%20$SUMMARY%0A----%20$SITE%0A%0A$URL"

# 打赏组件设置
donate:
  enable: false
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "/demo-assets/donate.webp"
  platforms:
    - name: "Ethereum"
      html: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-currency-ethereum">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M6 12l6 -9l6 9l-6 9z" />
          <path d="M6 12l6 -3l6 3l-6 2z" />
        </svg>
      color: "#8a92b2"
      qrcode: "0xexample_address"
    - name: "BitCoin"
      icon: "bitcoin"
      color: "#ee7c2f"
      qrcode: "example_address"
    - name: "支付宝"
      html: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-alipay">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M19 3h-14a2 2 0 0 0 -2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2v-14a2 2 0 0 0 -2 -2z" />
          <path d="M7 7h10" />
          <path d="M12 3v7" />
          <path d="M21 17.314c-2.971 -1.923 -15 -8.779 -15 -1.864c0 1.716 1.52 2.55 2.985 2.55c3.512 0 6.814 -5.425 6.814 -8h-6.604" />
        </svg>
      color: "#1677ff"
      qrcode: "example_alipay"
    - name: "微信支付"
      icon: "wechat"
      color: "#38ad5a"
      qrcode: "example_wechatpay"
    - name: "Credit Card"
      icon: "credit-card"
      color: "green"
      link: "https://candinya.com"

# 版权说明
copyright_notice:
  in_page:
    enable_at:
      - post
      - page

# 评论系统
comments:
  core:
    enable_at: 
      - index
      - post
      - page
    template:
      _shared: |
        <script>
          window.livereOptions = {
              refer: "https://alampy.com$PATH".replace(/\/index\.html$/, "/").replace(/^[a-zA-Z]+?\:\/\//, ""),
              site: "alampy.com$PATH".replace(/\/index\.html$/, "/"),
              eagerLoading: true
          };
          window.loadComments = () => {
              if (typeof LivereTower === 'undefined') {
                  var d = document, s = d.createElement('script');
                  s.src = 'https://cdn-city.livere.com/js/embed.dist.js';
                  (d.head || d.body).appendChild(s);
              } else {
                  window.LivereTower.start();
              }
          };
        </script>
      index: ""
      post: <div id="lv-container" class="kr-comments lazy-load" data-id="city" data-uid="MTAyMC81NTk3MC8zMjQzMw=="></div>
      page: <div id="lv-container" class="kr-comments lazy-load" data-id="city" data-uid="MTAyMC81NTk3MC8zMjQzMw=="></div>
  count:
    enable_at:
      []
      # - index
      # - post
    template:
      _shared: ""
      index: ""
      post: ""

# 访问数量统计
visit_count:
  enable_at:
    []
    # - index
    # - post
  template:
    _shared: ""
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: |
    <script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "999960a09fd44d63bc39abfe9a0e55a5"}'></script>
  footer: ""
  after_footer: ""
