---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: source/_posts/life
  label: Life
  create: documents
  match: "*.md"
  templates:
  - blog-post
- type: directory
  path: source/_posts
  label: Post
  create: documents
  match: "*.md"
  templates:
  - blog-post
upload_dir: source/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
