vendors:
  packages:
    disqusjs: 
      version: 1.2.6
    gitalk: 
      version: 1.7.2
    gitment: 
      version: 0.0.3
    twikoo: 
      version: 1.5.11
    valine: 
      version: 1.4.18
    "@waline/client": 
      version: 1.6.0
    bootstrap: 
      version: 3.3.4
    nprogress: 
      version: 0.2.0
    aplayer: 
      version: 1.10.1
    "@fancyapps/fancybox": 
      version: 3.5.7
    clipboard: 
      version: 2.0.6
    layui-src: 
      version: 2.5.5
    font-awesome: 
      version: 4.7.0
    jquery: 
      version: 3.6.0
    qrcode_js: 
      version: 1.0.0
    mermaid: 
      version: 9.1.1
    meting:
      version: 2.0.1