name: WebSub

on:
  check_run:
    types: [completed]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.check_run.name == 'fleek-ci'
    steps:
      - name: Publish
        run: curl -i https://pubsubhubbub.appspot.com/ -F "hub.mode=publish" -F "hub.url=https://alampy.com/atom.xml"