name: WebSub

on:
  check_run:
    types: [completed]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.check_run.app.slug == 'fleek-co'
    steps:
      - name: Publish
        run: |
          sleep 60 # Ensure files are updated to all nodes
          curl https://alampy.com/atom.xml > /dev/null # Ensure files are available
          curl -i https://pubsubhubbub.appspot.com/ -F "hub.mode=publish" -F "hub.url=https://alampy.com/atom.xml"